config/routes.rb
Rails.application.routes.draw do

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
                      length: { minimum: 2 }

  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }


  def completed?
    !completed_at.blank?
  end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items

  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 5 }

  def has_completed_items?
    todo_items.complete.size > 0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  before_action :find_todo_list

  def index
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding that todo list item."
      render action: :new
    end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_list = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item count not be deleted."
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_list_todo_items_path, notice: "Todo item marked as complete."
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private #Everything below is private

  def find_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="nav">
          <br class="clear" />
          <div class="panel panel-default">
            <div class="panel-heading"><h1 style="text-align: center;"><%= link_to "Odot", root_path %></h1></div>
            <div class="panel-body">
              <span class="btn btn-default btn-xs"><%= link_to "Todo Lists", todo_lists_path %></span>
              <span class="btn btn-default btn-xs pull-right"><%= link_to 'New Todo list', new_todo_list_path %></span>
            </div>

          </div>
        </div> <!-- end of nav -->

        <!-- change these to Bootstrap Alerts -->
        <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %>">
            <%= message %>
          </div>
        <% end %>

        <%= yield %>

      </div> <!-- end of col -->
    </div> <!-- end of row -->
  </div> <!-- end of container -->


</body>
</html>

app/views/todo_items/_form.html.erb
<div id="error_explanation">
  <% if @todo_item.errors.full_messages.count > 0 %>
  <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>
  <% end %>

  <ul>
    <% @todo_item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

<div style="margin: 0 auto;">
  <%= form.label :content, "Add List Item:" %>
  <%= form.text_field :content, class: "form-control"%>
  <%= form.submit "Add Item", class: "btn btn-success pull-right", style: "margin-top: 10px;" %>
</div>

app/views/todo_items/edit.html.erb
<h1><%= @todo_list.title %> - Editing Todo List Item</h1> 
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_items/index.html.erb
<h1><%= @todo_list.title %></h1>

<table class="todo_items table table-bordered table-stripped">
  <thead>
    <tr>
      <th>Completed?</th>
      <th>Content</th>
      <th>Functions</th>
    </tr>
  </thead>
  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr id="<%= dom_id(todo_item) %>">
        <td>
          <% if todo_item.completed? %>
            <%= todo_item.completed_at.strftime("%m/%d/%Y at %H:%M:%S") %>
          <% else %>
            <%= link_to "Mark Complete", complete_todo_list_todo_item_path(todo_item), method: :patch %>
          <% end %>
        </td>
        <td><%= todo_item.content %></td>
        <td style="text-align:center;">
          <span class="btn btn-warning btn-sm"><%= link_to icon('pencil-square-o'), edit_todo_list_todo_item_path(todo_item) %></span>
          <span class="btn btn-danger btn-sm"><%= link_to icon('trash'), todo_list_todo_item_path(todo_item), method: :delete, data: { confirm: "Are you sure?" } %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p class="btn btn-default btn-xs"><%= link_to "New Todo Item", new_todo_list_todo_item_path %></p>

app/views/todo_items/new.html.erb
<h1><%= @todo_list.title %></h1>
<h3 style="text-align:center;">Add Todo List Item:</h3>
<hr>
<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control", style: "resize: none" %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-default btn-primary pull-right" %>
    </div>
  <% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path, class: "btn btn-default"  %>
<%= link_to 'Show', @todo_list, class: "btn btn-default" %>

app/views/todo_lists/index.html.erb
<h1 class="well">All ToDo Lists</h1>

  <% @todo_lists.each do |todo_list| %>
    <div class="panel panel-default todo_list" id="<%= dom_id(todo_list) %>">
      <div class="panel-heading">
        <h2 style="display:inline;"><%= todo_list.title %></h2>
        <ul class="functions pull-right">
          <li class="btn btn-default btn-sm"><%= link_to icon('list'), todo_list_todo_items_path(todo_list) %></li>
          <li class="btn btn-default btn-sm"><%= link_to icon('eye'), todo_list %></li>
          <li class="btn btn-default btn-sm"><%= link_to icon('pencil-square-o'), edit_todo_list_path(todo_list) %></li>
          <li class="btn btn-default btn-sm"><%= link_to icon('trash'), todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div>
      <div class="panel-body">
        <p><%= todo_list.description %></p>
      </div>
    </div>
    <br class="clear">
  <% end %>
<br>

app/views/todo_lists/new.html.erb
<h1>Add New List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path, class: "btn btn-default" %>

app/views/todo_lists/show.html.erb
<h1>This is the SHOW PAGE - ToDo Lists</h1>
<h1><%= @todo_list.title %></h1>
<h3><%= @todo_list.description %></h3>

<% if @todo_list.has_incomplete_items? %>
<h4>Incomplete Items:</h4>

  <ul>
    <% @todo_list.todo_items.incomplete.each do |todo_item| %>
      <li><%= todo_item.content %></li>
    <% end %>
  </ul>
<% end %>

<% if @todo_list.has_completed_items? %>
<h4>Complete Items:</h4>

  <ul>
    <% @todo_list.todo_items.complete.each do |todo_item| %>
      <li><%= todo_item.content %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>